
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  template:
    metadata:
      name: product-service
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: aykanferhat/product-service
        env:
          - name: "DS_URL"
            value: "jdbc:mysql://mysql-service/ecommerce?characterEncoding=UTF-8"
          - name: "DS_USERNAME"
            value: "root"
          - name: "DS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        ports:
          - containerPort: 9090
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: product-service
