
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-service
  labels:
    app: shoppingcart-service
spec:
  replicas: 1
  template:
    metadata:
      name: shoppingcart-service
      labels:
        app: shoppingcart-service
    spec:
      containers:
      - name: shoppingcart-service
        image: aykanferhat/shoppingcart-service
        env:
          - name: "DS_URL"
            value: "jdbc:mysql://mysql-service/ecommerce?characterEncoding=UTF-8"
          - name: "DS_USERNAME"
            value: "root"
          - name: "DS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        ports:
          - containerPort: 8585
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: shoppingcart-service
