
server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: @application.name@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
  datasource:
    hikari:
      pool-name: hikaridp
      connection-timeout: 10000
      maximum-pool-size: 10
      driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: ${DS_URL:jdbc:mysql://localhost:3306/ecommerce?characterEncoding=UTF-8}
      username: ${DS_USERNAME:root}
      password: ${DS_PASSWORD:12345678}

---

spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: ${DS_URL:jdbc}
      username: ${DS_USERNAME}
      password: ${DS_PASSWORD}

---

spring:
  profiles: test
  datasource:
    hikari:
      jdbc-url: ${DS_URL}
      username: ${DS_USERNAME}
      password: ${DS_PASSWORD}



