apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
  labels:
    app: discount-service
spec:
  replicas: 1
  template:
    metadata:
      name: discount-service
      labels:
        app: discount-service
    spec:
      containers:
      - name: discount-service
        image: aykanferhat/discount-service
        env:
          - name: "DS_URL"
            value: "jdbc:mysql://mysql-service/ecommerce?characterEncoding=UTF-8"
          - name: "DS_USERNAME"
            value: "root"
          - name: "DS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        ports:
          - containerPort: 8088
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: discount-service
